"""initial audit ledger

Revision ID: fdebf92c8f1c
Revises:
Create Date: 2026-08-28 12:45:21.217520
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fdebf92c8f1c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("cycle_key", sa.String(length=80), nullable=False),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("passport_json", sa.JSON(), nullable=True),
        sa.Column("incident", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_runs_correlation_id"), "agent_runs", ["correlation_id"], unique=False
    )
    op.create_index(op.f("ix_agent_runs_cycle_key"), "agent_runs", ["cycle_key"], unique=True)
    op.create_table(
        "fills",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("broker_order_id", sa.String(length=80), nullable=False),
        sa.Column("activity_id", sa.String(length=100), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("broker_order_id", "activity_id"),
    )
    op.create_index(op.f("ix_fills_broker_order_id"), "fills", ["broker_order_id"], unique=False)
    op.create_table(
        "scheduler_leases",
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("owner_id", sa.String(length=80), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "auctions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("ranked_candidates_json", sa.JSON(), nullable=False),
        sa.Column("selected_candidate_id", sa.String(length=180), nullable=True),
        sa.Column("cash_won", sa.Boolean(), nullable=False),
        sa.Column("awarded_risk", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_run_id"),
    )
    op.create_table(
        "broker_orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=180), nullable=False),
        sa.Column("client_order_id", sa.String(length=48), nullable=False),
        sa.Column("broker_order_id", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("limit_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("environment_role", sa.String(length=20), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("broker_order_id"),
    )
    op.create_index(
        op.f("ix_broker_orders_agent_run_id"), "broker_orders", ["agent_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_broker_orders_client_order_id"), "broker_orders", ["client_order_id"], unique=True
    )
    op.create_table(
        "candidates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=180), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=12), nullable=False),
        sa.Column("score", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("maximum_loss", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("expected_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("liquidity_json", sa.JSON(), nullable=False),
        sa.Column("evidence_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_run_id", "candidate_id"),
    )
    op.create_index(
        op.f("ix_candidates_agent_run_id"), "candidates", ["agent_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_candidates_candidate_id"), "candidates", ["candidate_id"], unique=False
    )
    op.create_table(
        "equity_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("equity", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("cash", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("buying_power", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("portfolio_value", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("realized_pl", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("unrealized_pl", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("peak_equity", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("drawdown", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("official", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_equity_snapshots_agent_run_id"), "equity_snapshots", ["agent_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_equity_snapshots_observed_at"), "equity_snapshots", ["observed_at"], unique=False
    )
    op.create_table(
        "market_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=12), nullable=False),
        sa.Column("features_json", sa.JSON(), nullable=False),
        sa.Column("raw_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_market_snapshots_agent_run_id"), "market_snapshots", ["agent_run_id"], unique=False
    )
    op.create_table(
        "model_decisions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("regime", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("candidate_id", sa.String(length=180), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("thesis", sa.Text(), nullable=False),
        sa.Column("evidence_json", sa.JSON(), nullable=False),
        sa.Column("invalidation_json", sa.JSON(), nullable=False),
        sa.Column("maximum_holding_minutes", sa.Integer(), nullable=False),
        sa.Column("raw_response_hash", sa.String(length=64), nullable=False),
        sa.Column("validation_error", sa.String(length=80), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_run_id"),
    )
    op.create_table(
        "position_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("broker_position_id", sa.String(length=100), nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("market_value", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("unrealized_pl", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("raw_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_position_snapshots_agent_run_id"),
        "position_snapshots",
        ["agent_run_id"],
        unique=False,
    )
    op.create_table(
        "risk_decisions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("awarded_risk", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("reason_codes_json", sa.JSON(), nullable=False),
        sa.Column("checks_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_run_id"),
    )
    op.create_table(
        "system_states",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("execution_state", sa.String(length=32), nullable=False),
        sa.Column("kill_switch_active", sa.Boolean(), nullable=False),
        sa.Column("reconciliation_clean", sa.Boolean(), nullable=False),
        sa.Column("scheduler_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("incident_code", sa.String(length=80), nullable=True),
        sa.Column("incident_detail", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_states_agent_run_id"), "system_states", ["agent_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_system_states_observed_at"), "system_states", ["observed_at"], unique=False
    )
    op.create_table(
        "option_structures",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("candidate_row_id", sa.Integer(), nullable=False),
        sa.Column("strategy", sa.String(length=32), nullable=False),
        sa.Column("underlying", sa.String(length=12), nullable=False),
        sa.Column("expiration", sa.DateTime(timezone=True), nullable=False),
        sa.Column("legs_json", sa.JSON(), nullable=False),
        sa.Column("net_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("maximum_loss", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("maximum_profit", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("is_credit", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_row_id"],
            ["candidates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candidate_row_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("option_structures")
    op.drop_index(op.f("ix_system_states_observed_at"), table_name="system_states")
    op.drop_index(op.f("ix_system_states_agent_run_id"), table_name="system_states")
    op.drop_table("system_states")
    op.drop_table("risk_decisions")
    op.drop_index(op.f("ix_position_snapshots_agent_run_id"), table_name="position_snapshots")
    op.drop_table("position_snapshots")
    op.drop_table("model_decisions")
    op.drop_index(op.f("ix_market_snapshots_agent_run_id"), table_name="market_snapshots")
    op.drop_table("market_snapshots")
    op.drop_index(op.f("ix_equity_snapshots_observed_at"), table_name="equity_snapshots")
    op.drop_index(op.f("ix_equity_snapshots_agent_run_id"), table_name="equity_snapshots")
    op.drop_table("equity_snapshots")
    op.drop_index(op.f("ix_candidates_candidate_id"), table_name="candidates")
    op.drop_index(op.f("ix_candidates_agent_run_id"), table_name="candidates")
    op.drop_table("candidates")
    op.drop_index(op.f("ix_broker_orders_client_order_id"), table_name="broker_orders")
    op.drop_index(op.f("ix_broker_orders_agent_run_id"), table_name="broker_orders")
    op.drop_table("broker_orders")
    op.drop_table("auctions")
    op.drop_table("scheduler_leases")
    op.drop_index(op.f("ix_fills_broker_order_id"), table_name="fills")
    op.drop_table("fills")
    op.drop_index(op.f("ix_agent_runs_cycle_key"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_correlation_id"), table_name="agent_runs")
    op.drop_table("agent_runs")
    # ### end Alembic commands ###
